[package]
name = "k3scontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
docker-api = "0.9"
clap = { version = "3.2", features = ["derive"] }
