[package]
name = "k3scontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
const-concat = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
docker-api = "0.11.0"
clap = { version = "4", features = ["derive"] }
