[package]
name = "k3scontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2"
rand = "0.8"
random-string = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
docker-api = "0.11"
clap = { version = "4", features = ["derive"] }
